name: dns
author: terrier989 <terrier989@gmail.com>
homepage: https://github.com/terrier989/dns
description: A package for working with the DNS protocol.

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  dns-proxy: dns-proxy

dependencies:
  args: ^2.0.0
  meta: ^1.3.0
  ip:
    git: 
      url: git@github.com:tomialagbe/ip.git
      ref: f77ba4193968fb24a688c9b95fcc56ec12554dfc
  raw:
    git: git@github.com:tomialagbe/raw.git
  universal_io: ^2.0.1

dev_dependencies:
  test: ^1.16.8
